### ISSUE TITLE
Atom 0.176.0 crashes using go to declaration on Ubuntu 14.04

### ISSUE THREAD

**Issue by theblacklion** [mkleehammer/goto#21]
Atom 0.176.0 crashes using go to declaration on Ubuntu 14.04 within a Magento project.
I've disabled all other external packages but no luck.

For example:
1. Open app/code/core/Mage/Core/controllers/IndexController.php
2. Mark Mage_Core_Controller_Front_Action
3. Trigger go to declaration
4. Atom hangs using 100% cpu and crashes after a while.

Anything I can do to help?

**Comment by mkleehammer** [comment]
Before it offers symbols it has to index the entire project.  It sounds like it is not able to process a project this size.  Sorry.
